name: SMSpp_PyPSA_interface
channels:
  - conda-forge
  - gurobi
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - xarray<=2025.01.2
  - pypsa2smspp==0.0.2

  # for the exercises on pypsa
  - pypsa
  - glpk
  - gurobi  # not necessary but can ease the usability for some users
  - highspy

  # for jupyter
  - jupyter
  - ipython
  - ipykernel
