name: SMSpp_PyPSA_interface
channels:
  - conda-forge
  - gurobi
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - xarray<=2025.01.2
  # - pypsa2smspp  # after release decomment

  # for the exercises on pypsa
  - pypsa
  - glpk
  - gurobi  # not necessary but can ease the usability for some users
  - highspy

  # for jupyter
  - jupyter
  - ipython
  - ipykernel
  - pip:
    - git+https://github.com/SPSUnipi/pypsa2smspp  # use the latest version in the repository